Notes: Jenkins pipeline
project: popsci
services:
  backend:
    version: 1.0.0-develop.43
    image: 1.0.0-develop.43
    buildNumber: '43'
  frontend:
    version: Prototype.13
    image: Prototype.13
    buildNumber: '13'
  auth:
    version: master.18
    image: master.18
    buildNumber: '18'
  files:
    version: 1.4.0.15
    image: 1.4.0.15
    buildNumber: '15'
  users:
    version: 1.1.0-popsci.25
    image: 1.1.0-popsci.25
    buildNumber: '25'
