- name: build frontend microservice
  hosts: all
  connection: local
  gather_facts: yes
#  become: yes

  tasks:
    # Install collections with retry mechanism
    - name: install collections
      block:
        - name: install community.docker collection
          command: ansible-galaxy collection install community.docker -vvv
          register: result
          until: result.rc == 0
          retries: 3
          delay: 10
          ignore_errors: yes

        - name: install custom collection
          command: ansible-galaxy collection install git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,popsi-build -vvv
          register: result
          until: result.rc == 0
          retries: 3
          delay: 10
          ignore_errors: yes

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1

    #frontend build
    - name: build frontend
      include_role:
        name: bento.common.build_frontend
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER')}}"
        project_name: "{{ project_name }}"
        image_version: "{{ lookup('env','FE_VERSION') }}"
        container_name: "frontend"
        #container_build_path: "{{ workspace }}/{{ project_name }}-frontend"
        container_build_path: "{{ workspace }}/crdc-popsci-ui"
        dockerfile_path: "{{ workspace }}/playbooks/docker/dockerfiles/frontend-microservice-dockerfile"
        container_registry_url: "{{ ecr_repo }}"