---
- name: load data to neo4j db
  hosts: loader
  connection: local
  gather_facts: yes
  become: yes

  tasks:
    #install collections
    - name: install aws collection
      #command: ansible-galaxy collection install {{item}} --force-with-deps
      shell: "ansible-galaxy collection install {{ item | quote }} --force"
      loop:
        #-  amazon.aws
        #-  community.aws
        #-  community.docker
        - community.docker:<=3.4.3
        - amazon.aws:<=5.4.0
        - community.aws:<=3.2.0
        -  git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,v1.0

    #get db ip
    - name: get db ip
      include_role:
        name: bento.common.neo4j_ip
      vars:
        tier: "{{ lookup('env','TIER') }}"
        project_name: popsci
        database_name: "{{ project_name }}-{{ tier }}-neo4j"

    #load data
    - name: perform data loading
      include_role:
        name: bento.common.opensearch_loader
      vars:
        ansible_python_interpreter: /usr/bin/python3
        project_name:  "{{ lookup('env','PROJECT_NAME') }}"
        tier: "{{ lookup('env','TIER') }}"
        workspace: "{{ lookup('env','WORKSPACE') }}"
        region: us-east-1
        neo4j_user: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.neo4j_user', nested=true, region='us-east-1' ) }}"
        neo4j_password: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.neo4j_password', nested=true, region='us-east-1' ) }}"
        es_host: "https://{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.es_host', nested=true, region='us-east-1' ) }}"
        model_file1: "{{ workspace }}/popsci-model/model-desc/popsci-model.yml"
        model_file2: "{{ workspace }}/popsci-model/model-desc/popsci-model-props.yml"
        property_file: "config/props-popsci.yml"
        about_file: "{{ workspace }}/{{ project_name }}-frontend/src/content/{{ tier }}/aboutPagesContent.yaml"
        #indices_file: "{{ workspace }}/bento-backend/src/main/resources/yaml/es_indices_{{ project_name }}.yml"
        #indices_file: "{{ workspace }}/popsci-backend/src/main/resources/yaml/es_indices_popsci.yml"
        indices_file: "{{ workspace }}/popsci-backend/src/main/resources/yaml/es_indices_bento.yml"
